export const CART_ADD_POST_REQUEST = 'CART_ADD_POST_REQUEST';
export const CART_ADD_POST_SUCCESS = 'CART_ADD_POST_SUCCESS';
export const CART_ADD_POST_FAIL = 'CART_ADD_POST_FAIL';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';

export const CART_EMPTY = 'CART_EMPTY';

export const CART_REMOVE_POST_REQUEST = 'CART_REMOVE_POST_REQUEST';
export const CART_REMOVE_POST_SUCCESS = 'CART_REMOVE_POST_SUCCESS';
export const CART_REMOVE_POST_FAIL = 'CART_REMOVE_POST_FAIL';

export const CART_CHANGEQTY_REQUEST= 'CART_CHANGEQTY_REQUEST';
export const CART_CHANGEQTY_SUCCESS= 'CART_CHANGEQTY_SUCCESS';
export const CART_CHANGEQTY_FAIL= 'CART_CHANGEQTY_FAIL';
